#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/netatalk" ] || [ -e "/etc/init/netatalk.conf" ]; then
	if [ ! -e "/etc/init/netatalk.conf" ]; then
		update-rc.d netatalk start 50 2 3 4 5 . stop 50 1 . >/dev/null
	fi
	invoke-rc.d netatalk start || exit $?
fi
# End automatically added section
